name = "WeavingsOnManifolds"
uuid = "018322f1-b14b-4a22-a34f-561833de52ec"
authors = ["Matthias Himmelmann <65544132+matthiashimmelmann@users.noreply.github.com>"]
version = "0.1.0"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
Implicit3DPlotting = "d997a800-832a-4a4c-b340-7dddf3c1ad50"
